__verilog Pps7ddr {
    __INOUT(__int(15)) A;
    __int(4)         ARB;
    __INOUT(__int(3)) BA;
    __INOUT(__int(1)) CASB;
    __INOUT(__int(1)) CKE;
    __INOUT(__int(1)) CKN;
    __INOUT(__int(1)) CKP;
    __INOUT(__int(1)) CSB;
    __INOUT(__int(4)) DM;
    __INOUT(__int(32)) DQ;
    __INOUT(__int(4)) DQSN;
    __INOUT(__int(4)) DQSP;
    __INOUT(__int(1)) DRSTB;
    __INOUT(__int(1)) ODT;
    __INOUT(__int(1)) RASB;
    __INOUT(__int(1)) VRN;
    __INOUT(__int(1)) VRP;
    __INOUT(__int(1)) WEB;
};
__verilog Pps7dma {
    __int(1)         ACLK;
    __int(1)         DAREADY;
    __int(2)        *DATYPE;
    __int(1)        *DAVALID;
    __int(1)         DRLAST;
    __int(1)        *DRREADY;
    __int(2)         DRTYPE;
    __int(1)         DRVALID;
    __int(1)        *RSTN;
};
__verilog Pps7emiocan {
    __int(1)         PHYRX;
    __int(1)        *PHYTX;
};
__verilog Pps7emioenet {
    __int(1)         EXTINTIN;
    __int(1)         GMIICOL;
    __int(1)         GMIICRS;
    __int(1)         GMIIRXCLK;
    __int(8)         GMIIRXD;
    __int(1)         GMIIRXDV;
    __int(1)         GMIIRXER;
    __int(1)         GMIITXCLK;
    __int(8)        *GMIITXD;
    __int(1)        *GMIITXEN;
    __int(1)        *GMIITXER;
    __int(1)         MDIOI;
    __int(1)        *MDIOMDC;
    __int(1)        *MDIOO;
    __int(1)        *MDIOTN;
    __int(1)        *PTPDELAYREQRX;
    __int(1)        *PTPDELAYREQTX;
    __int(1)        *PTPPDELAYREQRX;
    __int(1)        *PTPPDELAYREQTX;
    __int(1)        *PTPPDELAYRESPRX;
    __int(1)        *PTPPDELAYRESPTX;
    __int(1)        *PTPSYNCFRAMERX;
    __int(1)        *PTPSYNCFRAMETX;
    __int(1)        *SOFRX;
    __int(1)        *SOFTX;
};
__verilog Pps7emiogpio {
    __int(64)        I;
    __int(64)       *O;
    __int(64)       *TN;
};
__verilog Pps7emioi2c {
    __int(1)         SCLI;
    __int(1)        *SCLO;
    __int(1)        *SCLTN;
    __int(1)         SDAI;
    __int(1)        *SDAO;
    __int(1)        *SDATN;
};
__verilog Pps7emiopjtag {
    __int(1)         TCK;
    __int(1)         TDI;
    __int(1)        *TDO;
    __int(1)        *TDTN;
    __int(1)         TMS;
};
__verilog Pps7emiosdio {
    __int(1)        *BUSPOW;
    __int(3)        *BUSVOLT;
    __int(1)         CDN;
    __int(1)        *CLK;
    __int(1)         CLKFB;
    __int(1)         CMDI;
    __int(1)        *CMDO;
    __int(1)        *CMDTN;
    __int(4)         DATAI;
    __int(4)        *DATAO;
    __int(4)        *DATATN;
    __int(1)        *LED;
    __int(1)         WP;
};
__verilog Pps7emiospi {
    __int(1)         MI;
    __int(1)        *MO;
    __int(1)        *MOTN;
    __int(1)         SCLKI;
    __int(1)        *SCLKO;
    __int(1)        *SCLKTN;
    __int(1)         SI;
    __int(1)        *SO;
    __int(1)         SSIN;
    __int(1)        *SSNTN;
    __int(3)        *SSON;
    __int(1)        *STN;
};
__verilog Pps7emiosramint {
    __int(1)         IN;
};
__verilog Pps7emiotrace {
    __int(1)         CLK;
    __int(1)        *CTL;
    __int(32)       *DATA;
};
__verilog Pps7emiottc {
    __int(3)         CLKI;
    __int(3)        *WAVEO;
};
__verilog Pps7emiouart {
    __int(1)         CTSN;
    __int(1)         DCDN;
    __int(1)         DSRN;
    __int(1)        *DTRN;
    __int(1)         RIN;
    __int(1)        *RTSN;
    __int(1)         RX;
    __int(1)        *TX;
};
__verilog Pps7emiousb {
    __int(2)        *PORTINDCTL;
    __int(1)         VBUSPWRFAULT;
    __int(1)        *VBUSPWRSELECT;
};
__verilog Pps7emiowdt {
    __int(1)         CLKI;
    __int(1)        *RSTO;
};
__verilog Pps7event {
    __int(1)         EVENTI;
    __int(1)        *EVENTO;
    __int(2)        *STANDBYWFE;
    __int(2)        *STANDBYWFI;
};
__verilog Pps7fclk {
    __int(4)        *CLK;
    __int(4)         CLKTRIGN;
    __int(4)        *RESETN;
};
__verilog Pps7fpgaid {
    __int(1)         LEN;
};
__verilog Pps7ftmd {
    __int(4)         TRACEINATID;
    __int(1)         TRACEINCLOCK;
    __int(32)        TRACEINDATA;
    __int(1)         TRACEINVALID;
};
__verilog Pps7ftmt {
    __int(32)        F2PDEBUG;
    __int(4)         F2PTRIG;
    __int(4)        *F2PTRIGACK;
    __int(32)       *P2FDEBUG;
    __int(4)        *P2FTRIG;
    __int(4)         P2FTRIGACK;
};
__verilog Pps7irq {
    __int(20)        F2P;
    __int(29)       *P2F;
};
__verilog Pps7m {
    __INOUT(__int(54)) IO;
};
__verilog Pps7maxigp {
    __int(1)         ACLK;
    __int(32)       *ARADDR;
    __int(2)        *ARBURST;
    __int(4)        *ARCACHE;
    __int(1)        *ARESETN;
    __int(12)       *ARID;
    __int(4)        *ARLEN;
    __int(2)        *ARLOCK;
    __int(3)        *ARPROT;
    __int(4)        *ARQOS;
    __int(1)         ARREADY;
    __int(2)        *ARSIZE;
    __int(1)        *ARVALID;
    __int(32)       *AWADDR;
    __int(2)        *AWBURST;
    __int(4)        *AWCACHE;
    __int(12)       *AWID;
    __int(4)        *AWLEN;
    __int(2)        *AWLOCK;
    __int(3)        *AWPROT;
    __int(4)        *AWQOS;
    __int(1)         AWREADY;
    __int(2)        *AWSIZE;
    __int(1)        *AWVALID;
    __int(12)        BID;
    __int(1)        *BREADY;
    __int(2)         BRESP;
    __int(1)         BVALID;
    __int(32)        RDATA;
    __int(12)        RID;
    __int(1)         RLAST;
    __int(1)        *RREADY;
    __int(2)         RRESP;
    __int(1)         RVALID;
    __int(32)       *WDATA;
    __int(12)       *WID;
    __int(1)        *WLAST;
    __int(1)         WREADY;
    __int(4)        *WSTRB;
    __int(1)        *WVALID;
};
__verilog Pps7ps {
    __INOUT(__int(1)) CLK;
    __INOUT(__int(1)) PORB;
    __INOUT(__int(1)) SRSTB;
};
__verilog Pps7saxiacp {
    __int(1)         ACLK;
    __int(32)        ARADDR;
    __int(2)         ARBURST;
    __int(4)         ARCACHE;
    __int(1)        *ARESETN;
    __int(3)         ARID;
    __int(4)         ARLEN;
    __int(2)         ARLOCK;
    __int(3)         ARPROT;
    __int(4)         ARQOS;
    __int(1)        *ARREADY;
    __int(2)         ARSIZE;
    __int(5)         ARUSER;
    __int(1)         ARVALID;
    __int(32)        AWADDR;
    __int(2)         AWBURST;
    __int(4)         AWCACHE;
    __int(3)         AWID;
    __int(4)         AWLEN;
    __int(2)         AWLOCK;
    __int(3)         AWPROT;
    __int(4)         AWQOS;
    __int(1)        *AWREADY;
    __int(2)         AWSIZE;
    __int(5)         AWUSER;
    __int(1)         AWVALID;
    __int(3)        *BID;
    __int(1)         BREADY;
    __int(2)        *BRESP;
    __int(1)        *BVALID;
    __int(64)       *RDATA;
    __int(3)        *RID;
    __int(1)        *RLAST;
    __int(1)         RREADY;
    __int(2)        *RRESP;
    __int(1)        *RVALID;
    __int(64)        WDATA;
    __int(3)         WID;
    __int(1)         WLAST;
    __int(1)        *WREADY;
    __int(8)         WSTRB;
    __int(1)         WVALID;
};
__verilog Pps7saxigp {
    __int(1)         ACLK;
    __int(32)        ARADDR;
    __int(2)         ARBURST;
    __int(4)         ARCACHE;
    __int(1)        *ARESETN;
    __int(6)         ARID;
    __int(4)         ARLEN;
    __int(2)         ARLOCK;
    __int(3)         ARPROT;
    __int(4)         ARQOS;
    __int(1)        *ARREADY;
    __int(2)         ARSIZE;
    __int(1)         ARVALID;
    __int(32)        AWADDR;
    __int(2)         AWBURST;
    __int(4)         AWCACHE;
    __int(6)         AWID;
    __int(4)         AWLEN;
    __int(2)         AWLOCK;
    __int(3)         AWPROT;
    __int(4)         AWQOS;
    __int(1)        *AWREADY;
    __int(2)         AWSIZE;
    __int(1)         AWVALID;
    __int(6)        *BID;
    __int(1)         BREADY;
    __int(2)        *BRESP;
    __int(1)        *BVALID;
    __int(32)       *RDATA;
    __int(6)        *RID;
    __int(1)        *RLAST;
    __int(1)         RREADY;
    __int(2)        *RRESP;
    __int(1)        *RVALID;
    __int(32)        WDATA;
    __int(6)         WID;
    __int(1)         WLAST;
    __int(1)        *WREADY;
    __int(4)         WSTRB;
    __int(1)         WVALID;
};
__verilog Pps7saxihp {
    __int(1)         ACLK;
    __int(32)        ARADDR;
    __int(2)         ARBURST;
    __int(4)         ARCACHE;
    __int(1)        *ARESETN;
    __int(6)         ARID;
    __int(4)         ARLEN;
    __int(2)         ARLOCK;
    __int(3)         ARPROT;
    __int(4)         ARQOS;
    __int(1)        *ARREADY;
    __int(2)         ARSIZE;
    __int(1)         ARVALID;
    __int(32)        AWADDR;
    __int(2)         AWBURST;
    __int(4)         AWCACHE;
    __int(6)         AWID;
    __int(4)         AWLEN;
    __int(2)         AWLOCK;
    __int(3)         AWPROT;
    __int(4)         AWQOS;
    __int(1)        *AWREADY;
    __int(2)         AWSIZE;
    __int(1)         AWVALID;
    __int(6)        *BID;
    __int(1)         BREADY;
    __int(2)        *BRESP;
    __int(1)        *BVALID;
    __int(3)        *RACOUNT;
    __int(8)        *RCOUNT;
    __int(64)       *RDATA;
    __int(1)         RDISSUECAP1EN;
    __int(6)        *RID;
    __int(1)        *RLAST;
    __int(1)         RREADY;
    __int(2)        *RRESP;
    __int(1)        *RVALID;
    __int(6)        *WACOUNT;
    __int(8)        *WCOUNT;
    __int(64)        WDATA;
    __int(6)         WID;
    __int(1)         WLAST;
    __int(1)        *WREADY;
    __int(1)         WRISSUECAP1EN;
    __int(8)         WSTRB;
    __int(1)         WVALID;
};
__emodule PS7 {
    Pps7ddr          DDR;
    Pps7dma          DMA0;
    Pps7dma          DMA1;
    Pps7dma          DMA2;
    Pps7dma          DMA3;
    Pps7emiocan      EMIOCAN0;
    Pps7emiocan      EMIOCAN1;
    Pps7emioenet     EMIOENET0;
    Pps7emioenet     EMIOENET1;
    Pps7emiogpio     EMIOGPIO;
    Pps7emioi2c      EMIOI2C0;
    Pps7emioi2c      EMIOI2C1;
    Pps7emiopjtag    EMIOPJTAG;
    Pps7emiosdio     EMIOSDIO0;
    Pps7emiosdio     EMIOSDIO1;
    Pps7emiospi      EMIOSPI0;
    Pps7emiospi      EMIOSPI1;
    Pps7emiosramint  EMIOSRAMINT;
    Pps7emiotrace    EMIOTRACE;
    Pps7emiottc      EMIOTTC0;
    Pps7emiottc      EMIOTTC1;
    Pps7emiouart     EMIOUART0;
    Pps7emiouart     EMIOUART1;
    Pps7emiousb      EMIOUSB0;
    Pps7emiousb      EMIOUSB1;
    Pps7emiowdt      EMIOWDT;
    Pps7event        EVENT;
    Pps7fclk         FCLK;
    Pps7fpgaid       FPGAID;
    Pps7ftmd         FTMD;
    Pps7ftmt         FTMT;
    Pps7irq          IRQ;
    Pps7maxigp       MAXIGP0;
    Pps7maxigp       MAXIGP1;
    Pps7m            M;
    Pps7ps           PS;
    Pps7saxiacp      SAXIACP;
    Pps7saxigp       SAXIGP0;
    Pps7saxigp       SAXIGP1;
    Pps7saxihp       SAXIHP0;
    Pps7saxihp       SAXIHP1;
    Pps7saxihp       SAXIHP2;
    Pps7saxihp       SAXIHP3;
};
