//
// Generated by Bluespec Compiler, version 2015.09.beta2 (build 34689, 2015-09-07)
//
// timestamp removed
//
// BVI format method schedule info:
// schedule portalIfc_messageSize_size  CF ( portalIfc_messageSize_size,
// 					  portalIfc_indications_0_first,
// 					  portalIfc_indications_0_deq,
// 					  portalIfc_indications_0_notEmpty,
// 					  portalIfc_indications_1_first,
// 					  portalIfc_indications_1_deq,
// 					  portalIfc_indications_1_notEmpty,
// 					  portalIfc_intr_status,
// 					  portalIfc_intr_channel,
// 					  ifc_heard,
// 					  ifc_heard2 );
//
// schedule portalIfc_indications_0_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_deq,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_heard,
// 					     ifc_heard2 );
// schedule portalIfc_indications_0_first  SB ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_1_first,
// 					   portalIfc_indications_1_deq,
// 					   portalIfc_indications_1_notEmpty,
// 					   ifc_heard,
// 					   ifc_heard2 );
// schedule portalIfc_indications_0_deq  C ( portalIfc_indications_0_deq );
//
// schedule portalIfc_indications_0_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_deq,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_heard2 );
// schedule portalIfc_indications_0_notEmpty  SB ( portalIfc_indications_0_deq,
// 						ifc_heard );
//
// schedule portalIfc_indications_1_first  CF ( portalIfc_messageSize_size,
// 					     portalIfc_indications_0_first,
// 					     portalIfc_indications_0_deq,
// 					     portalIfc_indications_0_notEmpty,
// 					     portalIfc_indications_1_first,
// 					     portalIfc_indications_1_notEmpty,
// 					     portalIfc_intr_status,
// 					     portalIfc_intr_channel,
// 					     ifc_heard,
// 					     ifc_heard2 );
// schedule portalIfc_indications_1_first  SB ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_deq  CF ( portalIfc_messageSize_size,
// 					   portalIfc_indications_0_first,
// 					   portalIfc_indications_0_deq,
// 					   portalIfc_indications_0_notEmpty,
// 					   ifc_heard,
// 					   ifc_heard2 );
// schedule portalIfc_indications_1_deq  C ( portalIfc_indications_1_deq );
//
// schedule portalIfc_indications_1_notEmpty  CF ( portalIfc_messageSize_size,
// 						portalIfc_indications_0_first,
// 						portalIfc_indications_0_deq,
// 						portalIfc_indications_0_notEmpty,
// 						portalIfc_indications_1_first,
// 						portalIfc_indications_1_notEmpty,
// 						portalIfc_intr_status,
// 						portalIfc_intr_channel,
// 						ifc_heard );
// schedule portalIfc_indications_1_notEmpty  SB ( portalIfc_indications_1_deq,
// 						ifc_heard2 );
//
// schedule portalIfc_intr_status  CF ( portalIfc_messageSize_size,
// 				     portalIfc_indications_0_first,
// 				     portalIfc_indications_0_notEmpty,
// 				     portalIfc_indications_1_first,
// 				     portalIfc_indications_1_notEmpty,
// 				     portalIfc_intr_status,
// 				     portalIfc_intr_channel );
// schedule portalIfc_intr_status  SB ( portalIfc_indications_0_deq,
// 				     portalIfc_indications_1_deq,
// 				     ifc_heard,
// 				     ifc_heard2 );
//
// schedule portalIfc_intr_channel  CF ( portalIfc_messageSize_size,
// 				      portalIfc_indications_0_first,
// 				      portalIfc_indications_0_notEmpty,
// 				      portalIfc_indications_1_first,
// 				      portalIfc_indications_1_notEmpty,
// 				      portalIfc_intr_status,
// 				      portalIfc_intr_channel );
// schedule portalIfc_intr_channel  SB ( portalIfc_indications_0_deq,
// 				      portalIfc_indications_1_deq,
// 				      ifc_heard,
// 				      ifc_heard2 );
//
// schedule ifc_heard  CF ( portalIfc_messageSize_size,
// 			 portalIfc_indications_0_first,
// 			 portalIfc_indications_0_deq,
// 			 portalIfc_indications_1_first,
// 			 portalIfc_indications_1_deq,
// 			 portalIfc_indications_1_notEmpty,
// 			 ifc_heard2 );
// schedule ifc_heard  C ( ifc_heard );
//
// schedule ifc_heard2  CF ( portalIfc_messageSize_size,
// 			  portalIfc_indications_0_first,
// 			  portalIfc_indications_0_deq,
// 			  portalIfc_indications_0_notEmpty,
// 			  portalIfc_indications_1_first,
// 			  portalIfc_indications_1_deq,
// 			  ifc_heard );
// schedule ifc_heard2  C ( ifc_heard2 );
//
//
// Ports:
// Name                         I/O  size props
// portalIfc_messageSize_size     O    16 const
// RDY_portalIfc_messageSize_size  O     1 const
// portalIfc_indications_0_first  O    32 reg
// RDY_portalIfc_indications_0_first  O     1 reg
// RDY_portalIfc_indications_0_deq  O     1 reg
// portalIfc_indications_0_notEmpty  O     1 reg
// RDY_portalIfc_indications_0_notEmpty  O     1 const
// portalIfc_indications_1_first  O    32 reg
// RDY_portalIfc_indications_1_first  O     1 reg
// RDY_portalIfc_indications_1_deq  O     1 reg
// portalIfc_indications_1_notEmpty  O     1 reg
// RDY_portalIfc_indications_1_notEmpty  O     1 const
// portalIfc_intr_status          O     1
// RDY_portalIfc_intr_status      O     1 const
// portalIfc_intr_channel         O    32
// RDY_portalIfc_intr_channel     O     1 const
// RDY_ifc_heard                  O     1
// RDY_ifc_heard2                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// portalIfc_messageSize_size_methodNumber  I    16 unused
// ifc_heard_v                    I    32 reg
// ifc_heard2_a                   I    16 reg
// ifc_heard2_b                   I    16 reg
// EN_portalIfc_indications_0_deq  I     1
// EN_portalIfc_indications_1_deq  I     1
// EN_ifc_heard                   I     1
// EN_ifc_heard2                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkEchoIndicationOutput(CLK,
			      RST_N,

			      portalIfc_messageSize_size_methodNumber,
			      portalIfc_messageSize_size,
			      RDY_portalIfc_messageSize_size,

			      portalIfc_indications_0_first,
			      RDY_portalIfc_indications_0_first,

			      EN_portalIfc_indications_0_deq,
			      RDY_portalIfc_indications_0_deq,

			      portalIfc_indications_0_notEmpty,
			      RDY_portalIfc_indications_0_notEmpty,

			      portalIfc_indications_1_first,
			      RDY_portalIfc_indications_1_first,

			      EN_portalIfc_indications_1_deq,
			      RDY_portalIfc_indications_1_deq,

			      portalIfc_indications_1_notEmpty,
			      RDY_portalIfc_indications_1_notEmpty,

			      portalIfc_intr_status,
			      RDY_portalIfc_intr_status,

			      portalIfc_intr_channel,
			      RDY_portalIfc_intr_channel,

			      ifc_heard_v,
			      EN_ifc_heard,
			      RDY_ifc_heard,

			      ifc_heard2_a,
			      ifc_heard2_b,
			      EN_ifc_heard2,
			      RDY_ifc_heard2);
  input  CLK;
  input  RST_N;

  // value method portalIfc_messageSize_size
  input  [15 : 0] portalIfc_messageSize_size_methodNumber;
  output [15 : 0] portalIfc_messageSize_size;
  output RDY_portalIfc_messageSize_size;

  // value method portalIfc_indications_0_first
  output [31 : 0] portalIfc_indications_0_first;
  output RDY_portalIfc_indications_0_first;

  // action method portalIfc_indications_0_deq
  input  EN_portalIfc_indications_0_deq;
  output RDY_portalIfc_indications_0_deq;

  // value method portalIfc_indications_0_notEmpty
  output portalIfc_indications_0_notEmpty;
  output RDY_portalIfc_indications_0_notEmpty;

  // value method portalIfc_indications_1_first
  output [31 : 0] portalIfc_indications_1_first;
  output RDY_portalIfc_indications_1_first;

  // action method portalIfc_indications_1_deq
  input  EN_portalIfc_indications_1_deq;
  output RDY_portalIfc_indications_1_deq;

  // value method portalIfc_indications_1_notEmpty
  output portalIfc_indications_1_notEmpty;
  output RDY_portalIfc_indications_1_notEmpty;

  // value method portalIfc_intr_status
  output portalIfc_intr_status;
  output RDY_portalIfc_intr_status;

  // value method portalIfc_intr_channel
  output [31 : 0] portalIfc_intr_channel;
  output RDY_portalIfc_intr_channel;

  // action method ifc_heard
  input  [31 : 0] ifc_heard_v;
  input  EN_ifc_heard;
  output RDY_ifc_heard;

  // action method ifc_heard2
  input  [15 : 0] ifc_heard2_a;
  input  [15 : 0] ifc_heard2_b;
  input  EN_ifc_heard2;
  output RDY_ifc_heard2;

  // signals for module outputs
  wire [31 : 0] portalIfc_indications_0_first,
		portalIfc_indications_1_first,
		portalIfc_intr_channel;
  wire [15 : 0] portalIfc_messageSize_size;
  wire RDY_ifc_heard,
       RDY_ifc_heard2,
       RDY_portalIfc_indications_0_deq,
       RDY_portalIfc_indications_0_first,
       RDY_portalIfc_indications_0_notEmpty,
       RDY_portalIfc_indications_1_deq,
       RDY_portalIfc_indications_1_first,
       RDY_portalIfc_indications_1_notEmpty,
       RDY_portalIfc_intr_channel,
       RDY_portalIfc_intr_status,
       RDY_portalIfc_messageSize_size,
       portalIfc_indications_0_notEmpty,
       portalIfc_indications_1_notEmpty,
       portalIfc_intr_status;

  // ports of submodule indicationPipes
  wire [31 : 0] indicationPipes_methods_heard2_enq_v,
		indicationPipes_methods_heard_enq_v,
		indicationPipes_portalIfc_indications_0_first,
		indicationPipes_portalIfc_indications_1_first,
		indicationPipes_portalIfc_intr_channel;
  wire [15 : 0] indicationPipes_portalIfc_messageSize_size,
		indicationPipes_portalIfc_messageSize_size_methodNumber;
  wire indicationPipes_EN_methods_heard2_enq,
       indicationPipes_EN_methods_heard_enq,
       indicationPipes_EN_portalIfc_indications_0_deq,
       indicationPipes_EN_portalIfc_indications_1_deq,
       indicationPipes_RDY_methods_heard2_enq,
       indicationPipes_RDY_methods_heard_enq,
       indicationPipes_RDY_portalIfc_indications_0_deq,
       indicationPipes_RDY_portalIfc_indications_0_first,
       indicationPipes_RDY_portalIfc_indications_1_deq,
       indicationPipes_RDY_portalIfc_indications_1_first,
       indicationPipes_portalIfc_indications_0_notEmpty,
       indicationPipes_portalIfc_indications_1_notEmpty,
       indicationPipes_portalIfc_intr_status;

  // value method portalIfc_messageSize_size
  assign portalIfc_messageSize_size =
	     indicationPipes_portalIfc_messageSize_size ;
  assign RDY_portalIfc_messageSize_size = 1'd1 ;

  // value method portalIfc_indications_0_first
  assign portalIfc_indications_0_first =
	     indicationPipes_portalIfc_indications_0_first ;
  assign RDY_portalIfc_indications_0_first =
	     indicationPipes_RDY_portalIfc_indications_0_first ;

  // action method portalIfc_indications_0_deq
  assign RDY_portalIfc_indications_0_deq =
	     indicationPipes_RDY_portalIfc_indications_0_deq ;

  // value method portalIfc_indications_0_notEmpty
  assign portalIfc_indications_0_notEmpty =
	     indicationPipes_portalIfc_indications_0_notEmpty ;
  assign RDY_portalIfc_indications_0_notEmpty = 1'd1 ;

  // value method portalIfc_indications_1_first
  assign portalIfc_indications_1_first =
	     indicationPipes_portalIfc_indications_1_first ;
  assign RDY_portalIfc_indications_1_first =
	     indicationPipes_RDY_portalIfc_indications_1_first ;

  // action method portalIfc_indications_1_deq
  assign RDY_portalIfc_indications_1_deq =
	     indicationPipes_RDY_portalIfc_indications_1_deq ;

  // value method portalIfc_indications_1_notEmpty
  assign portalIfc_indications_1_notEmpty =
	     indicationPipes_portalIfc_indications_1_notEmpty ;
  assign RDY_portalIfc_indications_1_notEmpty = 1'd1 ;

  // value method portalIfc_intr_status
  assign portalIfc_intr_status = indicationPipes_portalIfc_intr_status ;
  assign RDY_portalIfc_intr_status = 1'd1 ;

  // value method portalIfc_intr_channel
  assign portalIfc_intr_channel = indicationPipes_portalIfc_intr_channel ;
  assign RDY_portalIfc_intr_channel = 1'd1 ;

  // action method ifc_heard
  assign RDY_ifc_heard = indicationPipes_RDY_methods_heard_enq ;

  // action method ifc_heard2
  assign RDY_ifc_heard2 = indicationPipes_RDY_methods_heard2_enq ;

  // submodule indicationPipes
  mkEchoIndicationOutputPipes indicationPipes(.CLK(CLK),
					      .RST_N(RST_N),
					      .methods_heard2_enq_v(indicationPipes_methods_heard2_enq_v),
					      .methods_heard_enq_v(indicationPipes_methods_heard_enq_v),
					      .portalIfc_messageSize_size_methodNumber(indicationPipes_portalIfc_messageSize_size_methodNumber),
					      .EN_methods_heard_enq(indicationPipes_EN_methods_heard_enq),
					      .EN_methods_heard2_enq(indicationPipes_EN_methods_heard2_enq),
					      .EN_portalIfc_indications_0_deq(indicationPipes_EN_portalIfc_indications_0_deq),
					      .EN_portalIfc_indications_1_deq(indicationPipes_EN_portalIfc_indications_1_deq),
					      .RDY_methods_heard_enq(indicationPipes_RDY_methods_heard_enq),
					      .methods_heard_notFull(),
					      .RDY_methods_heard_notFull(),
					      .RDY_methods_heard2_enq(indicationPipes_RDY_methods_heard2_enq),
					      .methods_heard2_notFull(),
					      .RDY_methods_heard2_notFull(),
					      .portalIfc_messageSize_size(indicationPipes_portalIfc_messageSize_size),
					      .RDY_portalIfc_messageSize_size(),
					      .portalIfc_indications_0_first(indicationPipes_portalIfc_indications_0_first),
					      .RDY_portalIfc_indications_0_first(indicationPipes_RDY_portalIfc_indications_0_first),
					      .RDY_portalIfc_indications_0_deq(indicationPipes_RDY_portalIfc_indications_0_deq),
					      .portalIfc_indications_0_notEmpty(indicationPipes_portalIfc_indications_0_notEmpty),
					      .RDY_portalIfc_indications_0_notEmpty(),
					      .portalIfc_indications_1_first(indicationPipes_portalIfc_indications_1_first),
					      .RDY_portalIfc_indications_1_first(indicationPipes_RDY_portalIfc_indications_1_first),
					      .RDY_portalIfc_indications_1_deq(indicationPipes_RDY_portalIfc_indications_1_deq),
					      .portalIfc_indications_1_notEmpty(indicationPipes_portalIfc_indications_1_notEmpty),
					      .RDY_portalIfc_indications_1_notEmpty(),
					      .portalIfc_intr_status(indicationPipes_portalIfc_intr_status),
					      .RDY_portalIfc_intr_status(),
					      .portalIfc_intr_channel(indicationPipes_portalIfc_intr_channel),
					      .RDY_portalIfc_intr_channel());

  // submodule indicationPipes
  assign indicationPipes_methods_heard2_enq_v =
	     { ifc_heard2_a, ifc_heard2_b } ;
  assign indicationPipes_methods_heard_enq_v = ifc_heard_v ;
  assign indicationPipes_portalIfc_messageSize_size_methodNumber =
	     portalIfc_messageSize_size_methodNumber ;
  assign indicationPipes_EN_methods_heard_enq = EN_ifc_heard ;
  assign indicationPipes_EN_methods_heard2_enq = EN_ifc_heard2 ;
  assign indicationPipes_EN_portalIfc_indications_0_deq =
	     EN_portalIfc_indications_0_deq ;
  assign indicationPipes_EN_portalIfc_indications_1_deq =
	     EN_portalIfc_indications_1_deq ;
endmodule  // mkEchoIndicationOutput

